### ISSUE TITLE
Crash on Installation Step/Screen

### ISSUE THREAD

**Issue by Daltz333** [ThadHouse/WPILibInstaller-Avalonia#5]
```
System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=The system cannot find the file specified.
  Source=System.Diagnostics.Process
  StackTrace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WPILibInstaller_Avalonia.ViewModels.InstallPageViewModel.<>c__DisplayClass32_0.<RunVsCodeExtensionsSetup>b__8() in C:\Users\Dalton Smith\Documents\WPILibInstaller-Avalonia\WPILibInstaller-Avalonia\ViewModels\InstallPageViewModel.cs:line 506
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
````
on 
``Fixing up metadata`` when I just pressed "Next" without installing VS Code

**Comment by ThadHouse** [comment]
You had VS Code unchecked? Or using #4 and bypassing like that.

**Comment by Daltz333** [comment]
I used #4

**Comment by ThadHouse** [comment]
Ok. Then this isn't an issue, because that is not a supported scenario and caused by another bug. VS Code is now required to be installed, unlike before. We can have a discussion on if this is what we want, but for now thats the plan.
